### ISSUE TITLE
define Interchange6::Routes layout in config

### ISSUE THREAD

**Issue by hexfusion** [interchange/Dancer-Plugin-Interchange6#53]
Currently we can define the IC6 route template in the config.  I would like to be able to also define layout.  

```
plugins:
  Interchange6::Routes
    cart:
      layout: no_sidebar
      template: cart_new
```

```
 template $routes_config->{cart}->{template}, \%values,
    { layout => $routes_config->{cart}->{layout} };
```
